# Generated by Django 3.2.8 on 2021-10-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_num', models.IntegerField()),
                ('is_undergrad', models.BooleanField()),
                ('course_prereq', models.CharField(max_length=200)),
            ],
        ),
    ]
