# Generated by Django 3.2.8 on 2021-10-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_difficulty',
            field=models.IntegerField(default=2),
        ),
    ]
